### ISSUE TITLE
Question about pretrained model and results

### ISSUE THREAD

**Issue by ZhengHuanCS** [AndersonYong/URetinex-Net#1]
Hello, thanks for your great work.   
I have tried enhancing the low-light images of LOL testing set by using the provided pretrained model. The numerical results are listed as follows: (PSNR/SSIM/MAE 19.8416/0.8243/0.1166),  which is inconsistent with the reported results (21.3282/0.8348/0.0832). Could provide the pretrained model used in the paper?

**Comment by AndersonYong** [comment]
Hi, noted that the illumination adjustment in our model is determined by the specific ratio. Obviously, you can carefully tune the ratio to get the best results. I've update the newest evaluation code, please use it for evaluation. 
I've check the pretrained model and it worked well.

**Comment by ZhengHuanCS** [comment]
Thanks for your response.
